import { useMemo, useState } from 'react';
import { ArrowRight, Bot, Calculator } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
const money=(n:number)=>`$${Math.round(n).toLocaleString('en-US')}`;
export default function Simulator({price, passed}:{price:number|null; passed:number}){
 const navigate=useNavigate(); const [income,setIncome]=useState(''); const [expenses,setExpenses]=useState(''); const [risk,setRisk]=useState<'low'|'medium'|'high'>('medium'); const [months,setMonths]=useState('12');
 const r=useMemo(()=>{const i=Math.max(0,Number(income)||0),e=Math.max(0,Number(expenses)||0),spare=i?Math.max(0,i-e):0,m=spare?(risk==='low'?.1:risk==='medium'?.2:.3)*spare:100,h=Math.max(1,Number(months)||12),put=m*h,rate=risk==='low'?.03:risk==='medium'?.07:.12,growth=put*rate*(h/12)*.5;return{spare,monthly:m,put,low:put-growth*(risk==='high'?2:1),high:put+growth,drop:put*(risk==='high'?.2:risk==='medium'?.1:.05),h};},[income,expenses,risk,months]);
 return <section className="rd-detail rd-simulator" aria-labelledby="simulator-heading"><div className="rd-simulator-title"><div><p className="rd-eyebrow">Plan before you trade</p><h2 id="simulator-heading">Simple investment simulator</h2><p>Answer a few questions to see an educational estimate. Nothing here uses real money.</p><p className="rd-sim-market">Market context: BTC/USDT {price ? money(price) : 'waiting for a quote'} · {passed} tested strategies currently qualify</p></div><Calculator size={28}/></div><div className="rd-sim-form"><label>Monthly income <small>optional</small><input type="number" min="0" value={income} onChange={e=>setIncome(e.target.value)} placeholder="e.g. 4,000"/></label><label>Monthly expenses <small>rent, bills, food</small><input type="number" min="0" value={expenses} onChange={e=>setExpenses(e.target.value)} placeholder="e.g. 2,500"/></label><label>How long will you invest?<select value={months} onChange={e=>setMonths(e.target.value)}><option value="3">3 months</option><option value="12">1 year</option><option value="36">3 years</option><option value="60">5 years</option></select></label></div><div className="rd-sim-risk"><strong>How much risk feels okay?</strong><div>{(['low','medium','high'] as const).map(x=><button type="button" key={x} className={risk===x?'selected':''} onClick={()=>setRisk(x)}><b>{x==='low'?'Careful':x==='medium'?'Balanced':'Adventurous'}</b><span>{x==='low'?'Smaller ups and downs':x==='medium'?'A mix of growth and safety':'Bigger possible swings'}</span></button>)}</div></div><div className="rd-sim-results"><div><span>Suggested monthly amount</span><strong>{money(r.monthly)}</strong></div><div><span>Total put in</span><strong>{money(r.put)}</strong></div><div><span>Possible range after {r.h} months</span><strong>{money(r.low)} – {money(r.high)}</strong></div><div className="warning"><span>Possible temporary drop</span><strong>Up to {money(r.drop)}</strong></div></div><p className="rd-sim-note">This is a simple estimate, not a promise or personal financial advice. Prices can fall. {r.spare?`Your estimated spare cash is ${money(r.spare)} per month.`:'Add income and expenses for a more personal estimate.'}</p><button className="rd-primary rd-sim-cta" onClick={()=>navigate('/?view=autopilot')}><Bot size={17}/> Try the AI bot with virtual money <ArrowRight size={16}/></button></section>;
}
